# services:
#   - type: web
#     name: expense-tracker
#     runtime: python
#     buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
#     startCommand: "python manage.py runserver 0.0.0.0:$PORT"
#     envVars:
#       - key: DJANGO_SETTINGS_MODULE
#         value: Expense_Tracker.settings
#       - key: DEBUG
#         value: "False"
#       - key: SECRET_KEY
#         generateValue: true
#       - key: ALLOWED_HOSTS
#         fromService:
#           type: web
#           name: expense-tracker
#           property: host



services:
  - type: web
    name: expense-tracker
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Expense_Tracker.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        fromService:
          type: web
          name: expense-tracker
          property: host
      - key: CSRF_TRUSTED_ORIGINS
        fromService:
          type: web
          name: expense-tracker
          property: host
